### ISSUE TITLE
Shared memory allocation example (Tutorials/Gettingstarted/fpga_compile/part2_dpcpp_functor_usm)  not working  on Intel N6001 board  

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [oneapi-src/oneAPI-samples#2184] opened 2024-02-14 11:02 UTC
does Shared memory allocation work on Intel N6001 board? i am able to run board_test 
https://github.com/oneapi-src/oneAPI-samples/tree/master/DirectProgramming/C%2B%2BSYCL_FPGA/ReferenceDesigns/board_test

which has USM memory test. But I am not able to run 

- Tutorials/Gettingstarted/fpga_compile/part2_dpcpp_functor_usm

https://github.com/oneapi-src/oneAPI-samples/tree/master/DirectProgramming/C%2B%2BSYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part2_dpcpp_functor_usm

- Tutorials/GettingStarted/fpga_compile/part3_dpcpp_lambda_usm

https://github.com/oneapi-src/oneAPI-samples/tree/master/DirectProgramming/C%2B%2BSYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part3_dpcpp_lambda_usm

code seems to get stuck when executing

https://github.com/oneapi-src/oneAPI-samples/blob/d9ea61ab122ab030fbd74362bf9cd68766556117/DirectProgramming/C%2B%2BSYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part2_dpcpp_functor_usm/src/vector_add.cpp#L69

and 

https://github.com/oneapi-src/oneAPI-samples/blob/d9ea61ab122ab030fbd74362bf9cd68766556117/DirectProgramming/C%2B%2BSYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part3_dpcpp_lambda_usm/src/vector_add.cpp#L63

**Comment by mfmendoz-Intel** [comment] 2024-04-25 00:01
Hi, 
This is a duplicate of https://github.com/OFS/oneapi-asp/issues/140 issue, please track the updates in the OFS oneapi-asp repo.
Thanks

**Closed** 2024-11-25 20:04 UTC
Labels: question
